source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Report 2/Cleaning/Data_Cleaning_1.R")
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Report 2/Cleaning/CS_Type.R")

LTM2 <- LTM2 %>% 
  mutate(MH2WK_ANXDEP = case_when(PHQ4_MH2WK_ANX == 1 ~ 1, 
                                  PHQ4_MH2WK_DEP == 1 ~ 1, 
                                  TRUE ~ 0),
         EMPLOYBABYAGE = as.numeric(EMPLOYBABYAGE),
         EMPLOYBABYAGE_R = case_when(EMPLOYBABYAGE <= 6 ~ "6 weeks or less",
                                     EMPLOYBABYAGE > 6 ~ "More than 6 weeks"),
         ANYMISTREAT = case_when(MISTREATC1 == 1 ~ "Mistreated",
                                 MISTREATC2 == 1 ~ "Mistreated",
                                 MISTREATC3 == 1 ~ "Mistreated",
                                 MISTREATC4 == 1 ~ "Mistreated",
                                 MISTREATC5 == 1 ~ "Mistreated",
                                 MISTREATC6 == 1 ~ "Mistreated",
                                 MISTREATC7 == 1 ~ "Mistreated",
                                 MISTREATC8 == 1 ~ "Mistreated",
                                 MISTREATC9 == 1 ~ "No mistreatment"), 
         CSECTFEEL_NEG = case_when(CSECTFEELC2 == 1 | CSECTFEELC4 == 1|
                                     CSECTFEELC6 == 1 | CSECTFEELC8 == 1 ~ 1, 
                                   TRUE ~ 0),
         CSECTFEEL_POS = case_when(CSECTFEELC1 == 1 | CSECTFEELC3 == 1|
                                     CSECTFEELC5 == 1 | CSECTFEELC7 == 1 ~ 1, 
                                   TRUE ~ 0),
         INTENDLOCALE_R = case_when(INTENDLOCALE == 1 ~ "Yes", 
                                    INTENDLOCALE %in% c(2,3,4,5) ~ "No", 
                                    INTENDLOCALE == 95 ~ "Other", 
                                    INTENDLOCALE == 99 ~ "PNTA"),
         WIC_TREND = case_when(WICBEN == 1 & WICPPC1 == 1 ~ "Preg & Birth", 
                               WICBEN == 1 & WICPPC2 == 1 ~ "Preg & Birth",
                               WICBEN == 1 & WICPPC3 == 1 ~ "Preg Only",
                               WICBEN == 2 & WICPPC1 == 1 ~ "Birth Only",
                               WICBEN == 2 & WICPPC2 == 1 ~ "Birth Only", 
                               WICBEN == 2 & WICPPC3 == 1 ~ "None"), 
         WICANY = case_when(WICBEN == 1 ~ 1, 
                            WICPPC1 == 1 ~ 1, 
                            WICPPC2 == 1 ~ 1, 
                            WICBEN == 2 & WICPPC3 == 1 ~ 0,
                            WICBEN == 2 & WICPPC5 == 1 ~ 0,
                            WICBEN == 2 & WICPPC4 == 1 ~ 0), 
         ANYCOVIDVAC = case_when(COVIDVACC1 == 1 ~ 1, 
                                 COVIDVACC2 == 1 ~ 1, 
                                 COVIDVACC3 == 1 ~ 1, 
                                 TRUE ~ 0), 
         MORBPERSIST_A1_R = case_when(MORBPERSIST_A1 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A2_R = case_when(MORBPERSIST_A2 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A3_R = case_when(MORBPERSIST_A3 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A4_R = case_when(MORBPERSIST_A4 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A5_R = case_when(MORBPERSIST_A5 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A6_R = case_when(MORBPERSIST_A6 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A7_R = case_when(MORBPERSIST_A7 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A8_R = case_when(MORBPERSIST_A8 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A9_R = case_when(MORBPERSIST_A9 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A10_R = case_when(MORBPERSIST_A10 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A11_R = case_when(MORBPERSIST_A11 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A12_R = case_when(MORBPERSIST_A12 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A13_R = case_when(MORBPERSIST_A13 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A14_R = case_when(MORBPERSIST_A14 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A15_R = case_when(MORBPERSIST_A15 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A16_R = case_when(MORBPERSIST_A16 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A17_R = case_when(MORBPERSIST_A17 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A18_R = case_when(MORBPERSIST_A18 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A19_R = case_when(MORBPERSIST_A19 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A20_R = case_when(MORBPERSIST_A20 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A21_R = case_when(MORBPERSIST_A21 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A22_R = case_when(MORBPERSIST_A22 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A23_R = case_when(MORBPERSIST_A23 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A24_R = case_when(MORBPERSIST_A24 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A25_R = case_when(MORBPERSIST_A25 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         FAMFRISUPP_A1 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A1, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A1),
         FAMFRISUPP_A2 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A2, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A2),
         FAMFRISUPP_A3 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A3, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A3),
         FAMFRISUPP_A4 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A4, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A4),
         FAMFRISUPP_A1 = case_when(FAMFRISUPP_A1 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A1),
         FAMFRISUPP_A2 = case_when(FAMFRISUPP_A2 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A2),
         FAMFRISUPP_A3 = case_when(FAMFRISUPP_A3 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A3),
         FAMFRISUPP_A4 = case_when(FAMFRISUPP_A4 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A4),
         RELSUPP_A1 = case_when(RELSUPP_A1 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A1),
         RELSUPP_A2 = case_when(RELSUPP_A2 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A2),
         RELSUPP_A3 = case_when(RELSUPP_A3 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A3),
         RELSUPP_A4 = case_when(RELSUPP_A4 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A4),
         OTHERSUPP_A1 = case_when(OTHERSUPP_A1 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A1),
         OTHERSUPP_A2 = case_when(OTHERSUPP_A2 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A2),
         OTHERSUPP_A3 = case_when(OTHERSUPP_A3 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A3),
         OTHERSUPP_A4 = case_when(OTHERSUPP_A4 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A4),
         MAXSUPP_A1 = pmax(RELSUPP_A1, OTHERSUPP_A1, na.rm = T),
         MAXSUPP_A2 = pmax(RELSUPP_A2, OTHERSUPP_A2, na.rm = T),
         MAXSUPP_A3 = pmax(RELSUPP_A3, OTHERSUPP_A3, na.rm = T),
         MAXSUPP_A4 = pmax(RELSUPP_A4, OTHERSUPP_A4, na.rm = T), 
         PP_ANYSUPP = case_when(PPMHSUPP == 1 ~ 1, 
                                PPMEDSC1 == 1 ~ 1, 
                                PPMEDSC2 == 1 ~ 1,
                                TRUE ~ 0),
         PPMEDS_ANXDEP = case_when(PPMEDSC2 == 1 ~ 1, 
                                   PPMEDSC1 == 1 ~ 1, 
                                   TRUE ~ 0),
         PP_SUPP_ONLY = case_when(PPMHSUPP == 1 & PPMEDS_ANXDEP == 1 ~ "Both", 
                                  PPMHSUPP == 1 & PPMEDS_ANXDEP == 0 ~ "Counseling",
                                  PPMHSUPP == 2 & PPMEDS_ANXDEP == 1 ~ "Medication",
                                  PPMHSUPP == 2 & PPMEDS_ANXDEP == 0 ~ "Neither"),
         PP_UNMET_NEEDS = case_when(PP_ANYSUPP == 0 & MH2WK_ANXDEP == 1 ~ 1, 
                                    PP_ANYSUPP == 1 & MH2WK_ANXDEP == 1 ~ 0, 
                                    MH2WK_ANXDEP == 0 ~ 0))

