source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Report 2/Cleaning/Data_Cleaning_1.R")
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Report 2/Cleaning/CS_Type.R")
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Report 2/Cleaning/Dates2.R")

LTM2 <- LTM2 %>% 
  mutate(CURRWEIGHT_Q1 = case_when(is.na(CURRWEIGHT_LBS) ~ 2.20462 * CURRWEIGHT_KG, 
                                !is.na(CURRWEIGHT_LBS) ~ CURRWEIGHT_LBS), 
         CURRWEIGHT_Q2 = case_when(CURRENTWEIGHTQ2 == 1 ~ CURRENTWEIGHTQ2O,
                                      CURRENTWEIGHTQ2 == 2 ~ CURRENTWEIGHTQ2O * 2.20462),
         CURRWEIGHT_Q2 = case_when(CURRWEIGHT_Q2 <= 85 ~ NA, 
                                   TRUE ~ CURRWEIGHT_Q2),
         WEIGHTLOSS_Q2 = CURRWEIGHT_Q2 - PREPREG_WEIGHT,
         CURRREL_R = case_when(CURRREL == 1 ~ "Married", 
                               CURRREL == 2 ~ "Committed Partner",
                               CURRREL == 3 ~ "Separated/Single", 
                             CURRREL == 4 ~ "Separated/Single"),
         MH2WK_ANXDEP = case_when(PHQ4_MH2WK_ANX == 1 ~ 1, 
                                  PHQ4_MH2WK_DEP == 1 ~ 1, 
                                  TRUE ~ 0),
         EMPLOYBABYAGE = as.numeric(EMPLOYBABYAGE),
         EMPLOYBABYAGE_R = case_when(EMPLOYBABYAGE <= 6 ~ "6 weeks or less",
                                     EMPLOYBABYAGE > 6 ~ "More than 6 weeks"),
         ANYMISTREAT = case_when(MISTREATC1 == 1 ~ "Mistreated",
                                 MISTREATC2 == 1 ~ "Mistreated",
                                 MISTREATC3 == 1 ~ "Mistreated",
                                 MISTREATC4 == 1 ~ "Mistreated",
                                 MISTREATC5 == 1 ~ "Mistreated",
                                 MISTREATC6 == 1 ~ "Mistreated",
                                 MISTREATC7 == 1 ~ "Mistreated",
                                 MISTREATC8 == 1 ~ "Mistreated",
                                 MISTREATC9 == 1 ~ "No mistreatment"), 
         CSECTFEEL_NEG = case_when(CSECTFEELC2 == 1 | CSECTFEELC4 == 1|
                                     CSECTFEELC6 == 1 | CSECTFEELC8 == 1 ~ 1, 
                                   TRUE ~ 0),
         CSECTFEEL_POS = case_when(CSECTFEELC1 == 1 | CSECTFEELC3 == 1|
                                     CSECTFEELC5 == 1 | CSECTFEELC7 == 1 ~ 1, 
                                   TRUE ~ 0),
         INTENDLOCALE_R = case_when(INTENDLOCALE == 1 ~ "Yes", 
                                    INTENDLOCALE %in% c(2,3,4,5) ~ "No", 
                                    INTENDLOCALE == 95 ~ "Other", 
                                    INTENDLOCALE == 99 ~ "PNTA"),
         WIC_TREND = case_when(WICBEN == 1 & WICPPC1 == 1 ~ "Preg & Birth", 
                               WICBEN == 1 & WICPPC2 == 1 ~ "Preg & Birth",
                               WICBEN == 1 & WICPPC3 == 1 ~ "Preg Only",
                               WICBEN == 2 & WICPPC1 == 1 ~ "Birth Only",
                               WICBEN == 2 & WICPPC2 == 1 ~ "Birth Only", 
                               WICBEN == 2 & WICPPC3 == 1 ~ "None"), 
         WICANY = case_when(WICBEN == 1 ~ 1, 
                            WICPPC1 == 1 ~ 1, 
                            WICPPC2 == 1 ~ 1, 
                            WICBEN == 2 & WICPPC3 == 1 ~ 0,
                            WICBEN == 2 & WICPPC5 == 1 ~ 0,
                            WICBEN == 2 & WICPPC4 == 1 ~ 0), 
         ANYCOVIDVAC = case_when(COVIDVACC1 == 1 ~ 1, 
                                 COVIDVACC2 == 1 ~ 1, 
                                 COVIDVACC3 == 1 ~ 1, 
                                 TRUE ~ 0), 
         MORBPERSIST_A1_R = case_when(MORBPERSIST_A1 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A2_R = case_when(MORBPERSIST_A2 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A3_R = case_when(MORBPERSIST_A3 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A4_R = case_when(MORBPERSIST_A4 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A5_R = case_when(MORBPERSIST_A5 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A6_R = case_when(MORBPERSIST_A6 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A7_R = case_when(MORBPERSIST_A7 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A8_R = case_when(MORBPERSIST_A8 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A9_R = case_when(MORBPERSIST_A9 %in% c(1,2,3) ~ 1, 
                                      TRUE ~ 0),
         MORBPERSIST_A10_R = case_when(MORBPERSIST_A10 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A11_R = case_when(MORBPERSIST_A11 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A12_R = case_when(MORBPERSIST_A12 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A13_R = case_when(MORBPERSIST_A13 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A14_R = case_when(MORBPERSIST_A14 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A15_R = case_when(MORBPERSIST_A15 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A16_R = case_when(MORBPERSIST_A16 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A17_R = case_when(MORBPERSIST_A17 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A18_R = case_when(MORBPERSIST_A18 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A19_R = case_when(MORBPERSIST_A19 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A20_R = case_when(MORBPERSIST_A20 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A21_R = case_when(MORBPERSIST_A21 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A22_R = case_when(MORBPERSIST_A22 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A23_R = case_when(MORBPERSIST_A23 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A24_R = case_when(MORBPERSIST_A24 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         MORBPERSIST_A25_R = case_when(MORBPERSIST_A25 %in% c(1,2,3) ~ 1, 
                                       TRUE ~ 0),
         FAMFRISUPP_A1 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A1, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A1),
         FAMFRISUPP_A2 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A2, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A2),
         FAMFRISUPP_A3 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A3, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A3),
         FAMFRISUPP_A4 = case_when(CURRREL %in% c(1,2) ~ OTHERSUPP_A4, 
                                   CURRREL %in% c(3,4) ~ FFSUPP_A4),
         FAMFRISUPP_A1 = case_when(FAMFRISUPP_A1 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A1),
         FAMFRISUPP_A2 = case_when(FAMFRISUPP_A2 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A2),
         FAMFRISUPP_A3 = case_when(FAMFRISUPP_A3 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A3),
         FAMFRISUPP_A4 = case_when(FAMFRISUPP_A4 == 99 ~ NA, 
                                   TRUE ~ FAMFRISUPP_A4),
         RELSUPP_A1 = case_when(RELSUPP_A1 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A1),
         RELSUPP_A2 = case_when(RELSUPP_A2 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A2),
         RELSUPP_A3 = case_when(RELSUPP_A3 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A3),
         RELSUPP_A4 = case_when(RELSUPP_A4 == 99 ~ NA, 
                                TRUE ~ RELSUPP_A4),
         OTHERSUPP_A1 = case_when(OTHERSUPP_A1 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A1),
         OTHERSUPP_A2 = case_when(OTHERSUPP_A2 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A2),
         OTHERSUPP_A3 = case_when(OTHERSUPP_A3 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A3),
         OTHERSUPP_A4 = case_when(OTHERSUPP_A4 == 99 ~ NA, 
                                  TRUE ~ OTHERSUPP_A4),
         MAXSUPP_A1 = pmax(RELSUPP_A1, OTHERSUPP_A1, na.rm = T),
         MAXSUPP_A2 = pmax(RELSUPP_A2, OTHERSUPP_A2, na.rm = T),
         MAXSUPP_A3 = pmax(RELSUPP_A3, OTHERSUPP_A3, na.rm = T),
         MAXSUPP_A4 = pmax(RELSUPP_A4, OTHERSUPP_A4, na.rm = T), 
         PP_ANYSUPP = case_when(PPMHSUPP == 1 ~ 1, 
                                PPMEDSC1 == 1 ~ 1, 
                                PPMEDSC2 == 1 ~ 1,
                                TRUE ~ 0),
         PPMEDS_ANXDEP = case_when(PPMEDSC2 == 1 ~ 1, 
                                   PPMEDSC1 == 1 ~ 1, 
                                   TRUE ~ 0),
         PP_SUPP_ONLY = case_when(PPMHSUPP == 1 & PPMEDS_ANXDEP == 1 ~ "Both", 
                                  PPMHSUPP == 1 & PPMEDS_ANXDEP == 0 ~ "Counseling",
                                  PPMHSUPP == 2 & PPMEDS_ANXDEP == 1 ~ "Medication",
                                  PPMHSUPP == 2 & PPMEDS_ANXDEP == 0 ~ "Neither"),
         PP_UNMET_NEEDS = case_when(PP_ANYSUPP == 0 & MH2WK_ANXDEP == 1 ~ 1, 
                                    PP_ANYSUPP == 1 & MH2WK_ANXDEP == 1 ~ 0, 
                                    MH2WK_ANXDEP == 0 ~ 0), 
         NOSAFETY = case_when(SAFETY > 1 & SAFETY < 99 ~ 1, 
                              SAFETY == 1 ~ 0), 
         NOSAFETY2 = case_when(SAFETY > 2 & SAFETY < 99 ~ 1, 
                              SAFETY == 1 ~ 0,
                              SAFETY == 2 ~ 0), 
         NOSAFEBABY = case_when(SAFEBABY > 1 & SAFEBABY < 99 ~ 1, 
                                SAFEBABY == 1 ~ 0),
         INTERVAL0 = case_when(INTERVAL == 0 ~ "0 days", 
                               INTERVAL > 0 & INTERVAL < 9999 ~ "1+ days"),
         INTERVAL_7days = case_when(INTERVAL <= 7 ~ "Within 1 week", 
                                 INTERVAL < 9999 ~ "More than 1 week"),  
         R_INTERVAL = case_when(INTERVAL == 0 | INTERVAL == 1 ~ "0 - 1 days", 
                                INTERVAL > 1 & INTERVAL < 7 ~ "2 - 6 days", 
                                INTERVAL >= 7 & INTERVAL < 15 ~ "7 to 14 days", 
                                INTERVAL >= 15 & INTERVAL < 31 ~ "15 to 30 days", 
                                INTERVAL >= 31 & INTERVAL < 9999 ~ "31+ days"),
         R_INTERVAL = factor(R_INTERVAL, levels = c("0 - 1 days","2 - 6 days",
                                                    "7 to 14 days", 
                                                    "15 to 30 days","31+ days")),
         TRUSTTEAM_NONE = case_when(TRUSTTEAM > 1 & TRUSTTEAM < 99 ~ 1, 
                                    TRUSTTEAM == 1 ~ 0),
         ANYKIDS = case_when(FUTUREBIRTH > 0 & FUTUREBIRTH < 1000 ~ "Any", 
                             FUTUREBIRTH == 0 ~ "None"),
         NUMKIDS = case_when(FUTUREBIRTH == 0 ~ "None",
                             FUTUREBIRTH == 1 ~ "One",
                             FUTUREBIRTH == 2 ~ "Two",
                             FUTUREBIRTH > 0 & FUTUREBIRTH < 1000 ~ "3+"),
         BIRTHVIEW_R = case_when(BIRTHVIEW == 1 ~ "Agree",
                                 BIRTHVIEW == 2 ~ "Agree", 
                                 BIRTHVIEW == 3 ~ "Neither", 
                                 BIRTHVIEW == 4 ~ "Disagree", 
                                 BIRTHVIEW == 5 ~ "Disagree"),
         TIME_SINCE_BIRTH2 = round(TIME_SINCE_BIRTH),
         TIME_SINCE_BIRTH_MONTH = floor(TIME_SINCE_BIRTH2/4),
         TIME_SINCE_BIRTH_MONTH2 = case_when(TIME_SINCE_BIRTH_MONTH < 3 ~ 3,
                                             TIME_SINCE_BIRTH_MONTH > 24 ~ 24, 
                                             TRUE ~ TIME_SINCE_BIRTH_MONTH),
         TIME_SINCE_BIRTH_QUART = case_when(TIME_SINCE_BIRTH_MONTH <= 2 ~ "< 2 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 5 ~ "3-5 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 8 ~ "6-8 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 11 ~ "9-11 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 14 ~ "12 - 14 months",
                                            TIME_SINCE_BIRTH_MONTH <= 17 ~ "15 - 17 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 20 ~ "18 - 20 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 23 ~ "21 - 23 months", 
                                            TIME_SINCE_BIRTH_MONTH > 23 ~ "24+ months"),
         TIME_SINCE_BIRTH_HALF = case_when(TIME_SINCE_BIRTH_MONTH <= 2 ~ "< 2 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 5 ~ "3-5 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 11 ~ "6-11 months", 
                                            TIME_SINCE_BIRTH_MONTH <= 17 ~ "12 - 17 months",
                                            TIME_SINCE_BIRTH_MONTH <= 23 ~ "18 - 23 months", 
                                            TIME_SINCE_BIRTH_MONTH > 23 ~ "24+ months"),
         BOND_R = case_when(BOND > 1 & BOND < 5 ~ 1,
                            BOND == 1 ~ 0),
         MATHOSP_ANY = case_when(MATHOSPC2 == 1 ~ 1, 
                                 MATHOSPC3 == 1 ~ 1, 
                                 TRUE ~ 0),
         MATER_ANY = case_when(MATERC2 == 1 ~ 1, 
                               MATERC3 == 1 ~ 1, 
                               TRUE ~ 0), 
         RBABYCARETIME_B0 = as.factor(BABYCARETIME_B0),
         RBABYCARETIME_B1 = as.factor(BABYCARETIME_B1),
         RBABYCARETIME_B2 = as.factor(BABYCARETIME_B2),
         RBABYCARETIME_B3 = as.factor(BABYCARETIME_B3),
         RBABYCARETIME_B4 = as.factor(BABYCARETIME_B4),
         RBABYCARETIME_B5 = as.factor(BABYCARETIME_B5),
         RBABYCARETIME_B6 = as.factor(BABYCARETIME_B6),
         RBABYCARETIME_B7 = as.factor(BABYCARETIME_B7),
         RBABYCARETIME_B8 = as.factor(BABYCARETIME_B8),
         RBABYCARETIME_B9 = as.factor(BABYCARETIME_B9),
         CAREGIVE = case_when(CAREGIVE1C9 == 1 ~ 2, 
                              TRUE ~ CAREGIVE),
         CAREGIVE1C8 = case_when(MDID %in% c(601711, 101983, 202849,
                                             202934) ~ 0,
                                 TRUE ~ CAREGIVE1C8),
         CAREGIVE = case_when(MDID %in% c(202934, 101983) ~ 2,
                              TRUE ~ CAREGIVE),
         CAREGIVE1C5 = case_when(MDID == 601711 ~ 1, 
                                 TRUE ~ CAREGIVE1C5),
         ERRORCONCERN_A1_R = case_when(ERRORCONCERN_A1 == 1 ~ 0, 
                                       ERRORCONCERN_A1 < 5 ~ 1), 
         ERRORCONCERN_A2_R = case_when(ERRORCONCERN_A2 == 1 ~ 0, 
                                       ERRORCONCERN_A2 < 5 ~ 1),
         ERRORCONCERN_A3_R = case_when(ERRORCONCERN_A3 == 1 ~ 0, 
                                       ERRORCONCERN_A3 < 5 ~ 1),
         ERRORCONCERN_A4_R = case_when(ERRORCONCERN_A4 == 1 ~ 0, 
                                       ERRORCONCERN_A4 < 5 ~ 1),
         ERRORCONCERN_A5_R = case_when(ERRORCONCERN_A5 == 1 ~ 0, 
                                       ERRORCONCERN_A5 < 5 ~ 1),
         PPVISIT = case_when(PPVISIT == 99 ~ NA, 
                             TRUE ~ PPVISIT),
         LEARNED2 = case_when(LEARNED2 == 99 ~ NA, 
                              TRUE ~ LEARNED2),
         PREDISTANCE_R = case_when(PPLOCAL == 1 ~ PPDISTANCE, 
                                   PPLOCAL == 2 ~ PREDISTANCE,
                                   LEARNED2 > 1 & PPVISIT == 0 ~ PREDISTANCE),
         POSTDISTANCE_R = case_when(PPLOCAL == 1 ~ PPDISTANCE,
                                    PPLOCAL == 2 ~ POSTDISTANCE,
                                    LEARNED2 = 1 & PPVISIT > 0 ~ POSTDISTANCE),
         xPREDISTANCE_R = case_when(PREDISTANCE_R <= 5 ~ "5 miles or less",
                                    PREDISTANCE_R <= 10 ~ "6-10 miles",
                                    PREDISTANCE_R <= 20 ~ "11-20 miles",
                                    PREDISTANCE_R <= 40 ~ "21-40 miles",
                                    PREDISTANCE_R < 9999 ~ "41+ miles"),
         xPOSTDISTANCE_R = case_when(POSTDISTANCE_R <= 5 ~ "5 miles or less",
                                     POSTDISTANCE_R <= 10 ~ "6-10 miles",
                                     POSTDISTANCE_R <= 20 ~ "11-20 miles",
                                     POSTDISTANCE_R <= 40 ~ "21-40 miles",
                                     POSTDISTANCE_R < 9999 ~ "41+ miles"),
         POSTDISTANCE20 = case_when(POSTDISTANCE_R <= 20 ~ "20 or fewer", 
                                    POSTDISTANCE_R > 20 & POSTDISTANCE_R < 9999 ~ "21 or more"),
         PREDISTANCE20 = case_when(PREDISTANCE_R <= 20 ~ "20 or fewer", 
                                   PREDISTANCE_R > 20 & PREDISTANCE_R < 9999 ~ "21 or more"),
         POSTDISTANCE10 = case_when(POSTDISTANCE_R <= 10 ~ "10 or fewer", 
                                    POSTDISTANCE_R > 10 & POSTDISTANCE_R < 9999 ~ "11 or more"),
         PREDISTANCE10 = case_when(PREDISTANCE_R <= 10 ~ "10 or fewer", 
                                   PREDISTANCE_R > 10 & PREDISTANCE_R < 9999 ~ "11 or more"),
         STUDENT_R = case_when(STUDENT == 2 ~ "Student", 
                               STUDENT == 3 ~ "Student", 
                               STUDENT == 1 ~ "Not a student"),
         PARTSTUDENT_R = case_when(PARTSTUDENT == 2 ~ "Student", 
                                   PARTSTUDENT == 3 ~ "Student", 
                                   PARTSTUDENT == 1 ~ "Not a student"),
         QUALCARE_R = case_when(QUALCARE == 3 ~ 1, 
                                QUALCARE == 4 ~ 1, 
                                QUALCARE < 3 ~ 0),
         HCQUAL_R = case_when(HCQUAL == 3 ~ 1, 
                              HCQUAL == 4 ~ 1, 
                              HCQUAL < 3 ~ 0),
         PPCTIME = case_when(PPLOCAL == 1 ~ PPTIME, 
                             PPLOCAL != 1 ~ POSTTIME), 
         PNCTIME = case_when(PPLOCAL == 1 ~ PPTIME, 
                             PPLOCAL != 1 ~ PRETIME),
         xPPCTIME = case_when(PPLOCAL == 1 ~ xPPTIME, 
                              PPLOCAL != 1 ~ xPOSTTIME), 
         xPNCTIME = case_when(PPLOCAL == 1 ~ xPPTIME, 
                              PPLOCAL != 1 ~ xPRETIME),
         FUTUREBABYDIFF1_A1R = case_when(FUTUREBABYDIFF1_A1 > 90 ~ NA, 
                                         TRUE ~ FUTUREBABYDIFF1_A1), 
         FUTUREBABYDIFF1_A2R = case_when(FUTUREBABYDIFF1_A2 > 90 ~ NA, 
                                         TRUE ~ FUTUREBABYDIFF1_A2), 
         FUTUREBABYDIFF1_A3R = case_when(FUTUREBABYDIFF1_A3 > 90 ~ NA, 
                                         TRUE ~ FUTUREBABYDIFF1_A3), 
         FUTUREBABYDIFF1_A4R = case_when(FUTUREBABYDIFF1_A4 > 90 ~ NA, 
                                         TRUE ~ FUTUREBABYDIFF1_A4)
  ) %>% 
  rowwise() %>% 
  mutate(ANYMISTREAT_OB = sum(THREATC1, SHOUTC1, SHAREPRIVC1,
                              FORCEDC1, WHOPRIVC1, WITHHELDC1,
                              IGNOREC1, PABUSEC1, na.rm = T),
         ANYMISTREAT_MW = sum(THREATC2, SHOUTC2, SHAREPRIVC2,
                              FORCEDC2, WHOPRIVC2, WITHHELDC2,
                              IGNOREC2, PABUSEC2, na.rm = T), 
         ANYMISTREAT_N = sum(THREATC3, SHOUTC3, SHAREPRIVC3,
                             FORCEDC3, WHOPRIVC3, WITHHELDC3,
                             IGNOREC3, PABUSEC3, na.rm = T),
         TRAUMADET_SUM = sum(TRAUMADETC1, TRAUMADETC2, TRAUMADETC3, 
                             TRAUMADETC4, TRAUMADETC5, na.rm = T)
  )

LTM2 <- LTM2 %>% 
  mutate(ANYMISTREAT_OB = case_when(ANYMISTREAT_OB >= 1 ~ 1, 
                                    TRUE ~ 0), 
         ANYMISTREAT_MW =  case_when(ANYMISTREAT_MW >= 1 ~ 1, 
                                     TRUE ~ 0), 
         ANYMISTREAT_N =  case_when(ANYMISTREAT_N >= 1 ~ 1, 
                                    TRUE ~ 0),
         PROBABLEPTSD_R = case_when(TRAUMADET_SUM < 2 ~ "Negative PTSD screen", 
                                    TRAUMADET_SUM >= 2 ~ "Positive PTSD screen"))


