LTM2 <- LTM2 %>% 
  mutate(YEARBIRTH = as.numeric(YEARBIRTH),
         BIRTHDATE_M_NUM = case_when(BIRTHDATE_M == 1 ~ '01',
                                     BIRTHDATE_M == 2 ~ '02', 
                                     BIRTHDATE_M == 3 ~ '03', 
                                     BIRTHDATE_M == 4 ~ '04', 
                                     BIRTHDATE_M == 5 ~ '05', 
                                     BIRTHDATE_M == 6 ~ '06', 
                                     BIRTHDATE_M == 7 ~ '07', 
                                     BIRTHDATE_M == 8 ~ '08', 
                                     BIRTHDATE_M == 9 ~ '09', 
                                     BIRTHDATE_M == 10 ~ '10', 
                                     BIRTHDATE_M == 11 ~ '11', 
                                     BIRTHDATE_M == 12 ~ '12'),
         BIRTHDATE_D = case_when(nchar(BIRTHDATE_D) == 1 ~ paste0("0",BIRTHDATE_D),
                                 TRUE ~ as.character(BIRTHDATE_D)),
         BIRTHDATE_T = paste0(YEARBIRTH,BIRTHDATE_M_NUM,BIRTHDATE_D),
         BIRTHDATE = as.Date(BIRTHDATE_T, "%Y%m%d"), 
         xLastConnectionDate = case_when(grepl("/", xLastConnectionDate) ~ gsub("/","", xLastConnectionDate),
                                        TRUE ~ as.character(xLastConnectionDate)),
         SURVEYDATE = as.Date(xLastConnectionDate, "%Y%m%d"), 
         TIME_SINCE_BIRTH = difftime(SURVEYDATE, BIRTHDATE, units = "weeks"),
         TIME_SINCE_BIRTH = as.numeric(TIME_SINCE_BIRTH), 
         MONTH_6 = case_when(TIME_SINCE_BIRTH >= 24 ~ 1, TRUE ~ 0))
