---
title: "Output_Word"
author: "Ruby Barnard-Mayers"
date: "2025-09-08"
output: word_document
---

```{r include = F}
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/ApplyDictionary.R")
library(survey)
library(ggplot2)
library(kableExtra)
library(tidyr)
library(ggsurvey)
library(rlang)
library(knitr)
```

### Categorical Results 

``` {r echo = F, results = 'asis'} 
for(i in categorical){
  lab = dict2[dict2$variable == i,]$variable_label
  if(is_empty(lab)){
    print(print.cat(get({{i}})) %>%
            kbl(caption = i) %>%
            kable_styling())} else {
              print(print.cat(get({{i}})) %>%
                      kbl(caption = lab) %>%
                      kable_styling())
            }
  
  
}
```

# Continuous results
``` {r echo = F, results = 'asis'} 
for(i in continuous){
  lab = dict2[dict2$variable == i,]$variable_label
  if(is_empty(lab)){
    print(print.cont(get({{i}})) %>% 
            kbl(caption = i) %>% 
            kable_styling())} else {
              print(print.cont(get({{i}})) %>% 
                      kbl(caption = lab) %>% 
                      kable_styling())
            }
  
  
}
```

```{r, echo = F}
# LTM_final %>% ggplot(aes(x = LANGUAGE, group = RACE)) + geom_bar(aes(fill = RACE), position = "dodge") + coord_flip()

```

### Including Plots

