LTM2 <- LTM %>%
  mutate(DUEDATE = as.numeric(DUEDATE)/86400,
         BIRTHDATE = as.numeric(BIRTHDATE/86400), 
         DUEDATE = as.Date(DUEDATE, origin = "1582-10-14", "%Y-%"), 
         BIRTHDATE = as.Date(BIRTHDATE, origin = "1582-10-14"), 
         PARITY = case_when(NUMB_BIRTH == 1 ~ "Nulliparous", 
                            NUMB_BIRTH > 1 ~ "Multiparous", 
                            TRUE ~ "Missing"), 
         INCOME = as.numeric(INCOME),
         PREPREG_WEIGHT_A1 = as.numeric(PREPREG_WEIGHT_A1),
         PREPREG_WEIGHT_B1 = as.numeric(PREPREG_WEIGHT_B1),
         PREGWEIGHT_A1 = as.numeric(PREGWEIGHT_A1),
         PREGWEIGHT_B1 = as.numeric(PREGWEIGHT_B1),
         PREPREG_WEIGHT = case_when(is.na(PREPREG_WEIGHT_A1) ~ 2.20462 * PREPREG_WEIGHT_B1, 
                                    !is.na(PREPREG_WEIGHT_A1) ~ PREPREG_WEIGHT_A1), 
         PREG_WEIGHT = case_when(is.na(PREGWEIGHT_A1) ~ 2.20462 * PREGWEIGHT_B1,
                                 !is.na(PREGWEIGHT_A1) ~ PREGWEIGHT_A1),
         PREPREG_WEIGHT = round(PREPREG_WEIGHT, 5),
         PREG_WEIGHT = round(PREG_WEIGHT, 5),
         BIRTHWEIGHT_LBS = as.numeric(BIRTHWEIGHT_LBS),
         BIRTHWEIGHT_G = as.numeric(BIRTHWEIGHT_G),
         BIRTHWEIGHT_OZ = as.numeric(BIRTHWEIGHT_OZ),
         BIRTHWEIGHT_OZ = case_when(is.na(BIRTHWEIGHT_OZ) ~ 0, 
                                    TRUE ~ BIRTHWEIGHT_OZ),
         CURRWEIGHT_KG = as.numeric(CURRWEIGHT_KG),
         HEIGHT = (as.numeric(HEIGHT_FEET)*12) + as.numeric(HEIGHT_INCHES),
         BIRTHWEIGHT = case_when(!is.na(BIRTHWEIGHT_LBS) ~ BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495,
                                 !is.na(BIRTHWEIGHT_G) ~ BIRTHWEIGHT_G), 
         BIRTHWEIGHT = as.numeric(BIRTHWEIGHT),
         
         GESTAGE_WEEKS = as.numeric(GESTAGE_WEEKS),
         KG_any = case_when(!is.na(CURRWEIGHT_KG)  &  CURRWEIGHT_KG != 0~ 1, 
                            !is.na(PREGWEIGHT_B1) &  PREGWEIGHT_B1 != 0 ~ 1, 
                            !is.na(PREPREG_WEIGHT_B1) & PREPREG_WEIGHT_B1 != 0 ~ 1, 
                            TRUE ~ 0), 
         LEARNED1 = case_when(LEARNED1 == 99 ~ NA, TRUE ~ LEARNED1), 
         LABORINTC5 = as.numeric(LABORINTC5),
         LABCSEC = as.numeric(LABCSEC),
         CSECTIONTYPE = as.numeric(CSECTIONTYPE),
         VAGASSIST= as.numeric(VAGASSIST),
         CARESETTINGC1 = as.numeric(CARESETTINGC1),
         CARESETTINGC2 = as.numeric(CARESETTINGC2),
         CARESETTINGC3 = as.numeric(CARESETTINGC3),
         CARESETTINGC4 = as.numeric(CARESETTINGC4),
         CARESETTINGC5 = as.numeric(CARESETTINGC5),
         CARESETTINGC6 = as.numeric(CARESETTINGC6),
         CARESETTINGC7 = as.numeric(CARESETTINGC7),
         ANY_DOULA = case_when(DOULAC1 == 1 ~ 1, 
                               DOULAC2 == 1 ~ 1, 
                               DOULAC3 == 1 ~ 1, 
                               DOULAC4 == 1 ~ 0, 
                               TRUE ~ 0),
         CS_MIDWIFE = case_when(BIRTHATTEND == 4 & MODE2023 == 2 ~ 1, 
                                BIRTHATTEND == 5 & MODE2023 == 2 ~ 1,
                                TRUE ~ 0),
         PROVIDER = as.numeric(PROVIDER),
         PPVISITTIME1=as.numeric(PPVISITTIME1),
         PPVISITTIME2=as.numeric(PPVISITTIME2),
         
         PPVISITTIME = case_when(!is.na(PPVISITTIME1) ~ PPVISITTIME1,
                                 !is.na(PPVISITTIME2) ~ PPVISITTIME2),
         
         # Flag 1s
         F1_SPEED = case_when(TotalDurationSec < 19*60 ~ 1, 
                              TotalDurationSec >= 19*60 ~ 0),
         F1_USKG_ANY = case_when(BIRTHCOUNTRY == 1 & KG_any == 1 ~ 1, 
                                 TRUE ~ 0),
         F1_NOTRIBALAFF = case_when(RACE == "AIAN" & "99" %in% AIAN  ~ 1,
                                    RACE == "AIAN" & AIAN == "99 " ~ 1,
                                    RACE == "AIAN" & AIAN == " 99" ~ 1,
                                    RACE == "AIAN" & AIAN == "11" ~ 1,
                                    RACE == "AIAN" & AIAN == "Na" ~ 1,
                                    RACE == "AIAN" & AIAN == "None" ~ 1,
                                    RACE == "AIAN" & AIAN == "N/A" ~ 1,
                                    RACE == "AIAN" & AIAN == "None Officially" ~ 1,
                                    RACE == "AIAN" & AIAN == "Don't Have One" ~ 1,
                                    RACE == "AIAN" & AIAN == "American Indian /African American/white" ~ 1,
                                    RACE == "AIAN" & AIAN == " " ~ 1,
                                    RACE == "AIAN" & AIAN == "African American" ~ 1,
                                    RACE == "AIAN" & AIAN == "" ~ 1,
                                    RACE == "AIAN" & AIAN == "American" ~ 1,
                                    RACE == "AIAN" & AIAN == "American Indian" ~ 1,
                                    TRUE ~ 0),
         
         # Flag 2s
         F2_GA_EXT = case_when(GESTAGE_WEEKS < 27 ~ 1, 
                               GESTAGE_WEEKS > 42 ~ 1, 
                               TRUE ~ 0),
         F2_HT_EXT = case_when(HEIGHT <= 57 ~ 1, 
                               HEIGHT >= 77 ~ 1, 
                               TRUE ~ 0),
         F2_WT_EXT = case_when(PREGWEIGHT_A1 <= 115 ~ 1,
                               2.20462 * PREGWEIGHT_B1 <= 115 ~ 1,
                               PREGWEIGHT_A1 >= 340 ~ 1, 
                               2.20462 * PREGWEIGHT_B1 >= 340 ~ 1, 
                               
                               PREPREG_WEIGHT_A1 <= 94 ~ 1, 
                               2.20462 * PREPREG_WEIGHT_B1 <= 94 ~ 1,
                               PREPREG_WEIGHT_A1 >= 317 ~ 1, 
                               2.20462 * PREPREG_WEIGHT_B1  >= 317 ~ 1,
                               
                               TRUE ~ 0),
         F2_BW_EXT = case_when(BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 <= 970 ~ 1, 
                               BIRTHWEIGHT_G <= 970 ~ 1,
                               
                               BIRTHWEIGHT_G >= 4620 & PREPREG_PHYSCONDC2 == 0 & 
                                 PREGCONDITIONC1 == 0 ~ 1,
                               
                               BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 >= 4620 & 
                                 PREPREG_PHYSCONDC2 == 0 & PREGCONDITIONC1 == 0 ~ 1,
                               
                               BIRTHWEIGHT_G >= 4800 & PREPREG_PHYSCONDC2 == 1 ~ 1,
                               BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 >= 4800 & PREPREG_PHYSCONDC2 == 1 ~ 1,
                               
                               BIRTHWEIGHT_G >= 4800 & PREGCONDITIONC1 == 1 ~ 1,
                               BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 >= 4800 & PREGCONDITIONC1 == 1 ~ 1,
                               TRUE ~ 0),
         
         F2_MCAID_INC_EXT = case_when(INCOME > 150000 & INSURC2 == 1 ~ 1, 
                                      TRUE ~ 0), 
         F2_VLBNICU = case_when(BIRTHWEIGHT_G < 1500 & NICU == 3 ~ 1, 
                                BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 < 1500 & NICU == 3 ~ 1,
                                TRUE ~ 0), 
         F2_VLBHOSP = case_when(BIRTHWEIGHT_G < 1500 & BABYHOSP < 4 ~ 1, 
                                BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 < 1500 & BABYHOSP < 4 ~ 1,
                                TRUE ~ 0), 
         
         # Flag 3s
         F3_PNCB4LEARN = case_when(as.numeric(LEARNED2) < as.numeric(LEARNED1) ~ 1, 
                                   TRUE ~ 0),
         F3_EARLYPNC = case_when(LEARNED2 > 1 & LEARNED2 <= 4 ~ 1, 
                                 TRUE ~ 0),
         F3_NO_PNC = case_when(LEARNED2 == 1 ~ 1, 
                               TRUE ~ 0),
         F3_PREGWT = case_when( 2.20462 * PREGWEIGHT_B1 <= 129 & F2_WT_EXT == 0 ~ 1, 
                                PREGWEIGHT_A1 <= 129 & F2_WT_EXT == 0 ~ 1, 
                                TRUE ~ 0),
         F3_WTDIFF = case_when(PREGWEIGHT_A1 <= PREPREG_WEIGHT_A1 ~ 1, 
                               PREGWEIGHT_B1 <= PREPREG_WEIGHT_B1 ~ 1, 
                               PREGWEIGHT_A1 <= PREPREG_WEIGHT_B1 ~ 1, 
                               PREGWEIGHT_B1 <= PREPREG_WEIGHT_A1 ~ 1, 
                               TRUE ~ 0 ),
         
         F3_HT = case_when(HEIGHT >= 70 & HEIGHT < 77 ~ 1, 
                           TRUE ~ 0),
         F3_LBW_NICU = case_when(BIRTHWEIGHT_G >= 1500 & BIRTHWEIGHT < 2500 & 
                                   NICU == 3 ~ 1, 
                                 BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 >= 1500 & 
                                   BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 < 2500 & 
                                   NICU == 3 ~ 1,
                                 TRUE ~ 0),
         F3_LBW_DAYS = case_when(BIRTHWEIGHT >= 1500 & BIRTHWEIGHT < 2500 & 
                                   BABYHOSP < 4 ~ 1, 
                                 BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 >= 1500 & 
                                   BIRTHWEIGHT_LBS*453.59237 + BIRTHWEIGHT_OZ*28.3495 < 2500 &
                                   BABYHOSP < 4 ~ 1, 
                                 TRUE ~ 0),
         
         F3_VAGASSIST = case_when(VAGASSIST %in% c(1,2) ~ 1, 
                                  TRUE ~ 0),
         F3_GAFOOD = case_when(CURRENTFEEDC4 == 0 & BABY_SURVEYAGE_MONTHS >= 7  ~ 1, 
                               TRUE ~ 0),
         F3_INC_MCAID = case_when(INCOME < 150000 & INCOME >= 100000 & 
                                    INSURC2 == 1 ~ 1, 
                                  TRUE ~ 0),
         F3_INC_PAN = case_when(INCOME >= 150000 & Source %in% c(4,5,6,7) ~ 1, 
                                TRUE ~ 0),
         NEED_F = case_when(SOCIALNEEDC1 == 1 ~ 1, 
                            SOCIALNEEDC2 == 1 ~ 1,
                            SOCIALNEEDC3 == 1 ~ 1,
                            SOCIALNEEDC4 == 1 ~ 1,
                            TRUE ~ 0),
         F3_INC_NEEDS = case_when(INCOME >= 150000 & NEED_F == 1 ~ 1,
                                  TRUE ~ 0),
         F3_PRE_HYPER = case_when(PREPREG_PHYSCONDC1 == 1 ~ 1,
                                  TRUE ~ 0),
         F3_PRE_DIABETES = case_when(PREPREG_PHYSCONDC2 == 1 ~ 1,
                                     TRUE ~ 0),
         F3_CS_LABOR = case_when(LABCSEC == 1 & CSECTIONTYPE == 1 ~ 1, 
                                 TRUE ~ 0),
         
         F3_VAGEXAM = case_when(LABORINTC5 == 0 ~ 1, 
                                TRUE ~ 0),
         F3_TERM_NICU = case_when(GESTAGE_WEEKS <= 42 & GESTAGE_WEEKS >= 37 & NICU %in% c(1,2) ~ 1, 
                                  TRUE ~ 0),
         F3_PPTVISITS = case_when(PPVISIT >= 4 ~ 1, 
                                  TRUE ~ 0),
         F3_MISSING_BW = case_when(is.na(BIRTHWEIGHT) ~ 1, 
                                   TRUE ~ 0),
         F3_MISSING_LABORHRS = case_when(LABORLENGTH == 999.00 ~ 1, 
                                         LABORLENGTH == "#NULL!" ~ 1,
                                         TRUE ~ 0),
         F3_MISSING_MOMDAYS = case_when(DAYSHOSP == 98~ 1, 
                                        DAYSHOSP == 99 ~ 1,
                                        TRUE ~ 0),
         F3_MISSING_BABYDAYS = case_when(BABYHOSP == 98 ~ 1, 
                                         BABYHOSP == 99 ~ 1,
                                         TRUE ~ 0)) 