source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Cleaning/Helpful_Functions.R")

# Data Read in &  Get rid of identifying information ----
LTM <- read.csv("/Users/rubybarnard-mayers/Documents/2025-2026/LTM/Data_FINAL.csv") 

LTM1 <- LTM %>% 
  mutate(MDID = as.character(MDID))

miss_vars <- dict2[dict2$missing == 99999,"variable"] %>% subset(!is.na(variable)) 

# Identify text response columns ending for other ----
# Don't want to convert these columns to numeric
ends_o <- LTM1[str_ends(colnames(LTM1), "O")]  %>% colnames()

# Create dataset of just text responses and MDID (so we can merge back) ----
# Don't want to convert these columns to numeric
LTM_ignore <- LTM1 %>% 
  select(c(all_of(ends_o), MDID, DOULA3, INDUCE6, REPEATCSEC,
           ResLanguage, ANYTHINGELSE, DISABILITYCOND)) 

# List of columns that are text only 
ignores <- LTM_ignore %>% 
  select(-c(MDID)) %>% 
  colnames() 

# Create dataset of the numeric columns to convert----
LTM_keep <- LTM1 %>% 
  select(-c(all_of(ignores)), MDID)

# Create list of column names to convert to numeric
tochange <- LTM_keep %>% select(-c(MDID)) %>%
  colnames()

# Convert all columns to numeric
for(i in tochange){
  LTM_keep[[i]] <- as.numeric(LTM_keep[[i]])
}

sn_cols <- LTM_keep %>% 
  select(starts_with("SN")) %>% 
  colnames()

for(i in sn_cols){
  LTM_keep[[i]] <- ifelse(LTM_keep[[i]] == 2, 0, 
                          ifelse(LTM_keep[[i]] == 99, NA, 
                                 ifelse(LTM_keep[[i]] == 99999, NA, 1)))
}


# merge the text columns back in with the numeric ones
LTM1 <- LTM_keep %>% 
  full_join(LTM_ignore, join_by(MDID))

# Recode variables ----
LTM1$BOTHER_R1 <- rev.likert("BOTHER_A1", dat = LTM1)
LTM1$BOTHER_R2 <- rev.likert("BOTHER_A2", dat = LTM1)
LTM1$BOTHER_R3 <- rev.likert("BOTHER_A3", dat = LTM1)
LTM1$BOTHER_R4 <- rev.likert("BOTHER_A4", dat = LTM1)

# Convert missing ----
LTM1 <- convert.miss(LTM1, c('RESPECT', 'KNOWLEDGE', 'HEARD', 
                             'DECISIONS', 'CONSENT', 'INFORMED',
                             'TIMELINESS', 'TRUST', 'FEEDING',
                             'SAFE', 'DISCRIMINATION', 'NEGLECT'), 99)
LTM1 <- convert.miss(LTM1, c("TIMELINESS"), 97)
LTM1 <- convert.miss(LTM1, miss_vars$variable, 99999)

# All data ----
LTM2 <- LTM1 %>% 
  mutate(
    PARITY = case_when(NUMB_BIRTH == 1 ~ "Nulliparous",
                       NUMB_BIRTH > 1 ~ "Multiparous",
                       TRUE ~ "Missing"),
    DUEDATE_Y = as.numeric(DUEDATE_Y),
    DUEDATE_M = as.numeric(DUEDATE_M),
    DUEDATE_D = as.numeric(DUEDATE_D),
    DUEDATE = as.Date(paste0(DUEDATE_M,"/", DUEDATE_D, "/",DUEDATE_Y), "m%/%d/%Y"),
    YEARBIRTH = as.numeric(YEARBIRTH),
    BIRTHDATE_M = as.numeric(BIRTHDATE_M),
    BIRTHDATE_D = as.numeric(BIRTHDATE_D),
    BIRTHDATE = as.Date(paste0(BIRTHDATE_M,"/", BIRTHDATE_D, "/",YEARBIRTH), "m%/%d/%Y"),
    GESTAGE_F = case_when(GESTAGE_WEEKS < 27 ~ 1, GESTAGE_WEEKS > 43 ~ 1, TRUE ~ 0), 
    GESTAGE_R = case_when(GESTAGE_F == 1 ~ NA, 
                          GESTAGE_F == 0 ~ GESTAGE_WEEKS),
    GESTAGE_R_cont = as.numeric(GESTAGE_R),
    xGESTAGE_R = case_when(GESTAGE_R_cont <= 34 ~ "Early Preterm", 
                           GESTAGE_R_cont < 37 ~ "Preterm", 
                           GESTAGE_R_cont <= 38 ~ "Early Term", 
                           GESTAGE_R_cont <= 40 ~ "Term", 
                           GESTAGE_R_cont <= 41 ~ "Late Term", 
                           GESTAGE_R_cont >= 42 ~ "Postterm"),
    HEIGHT = (HEIGHT_FEET*12) + HEIGHT_INCHES, 
    INCCAT2 = case_when(INCCAT == 5 | INCCAT == 6 ~ "$100,000+",
                        INCCAT == 4 | INCCAT == 3 ~ "$50,000 to $99,999",
                        INCCAT == 2 ~ "$25,000 to $49,999",
                        INCCAT == 1 ~ "Less than $25,000"), 
    AGE_ATBIRTH = floor(as.numeric(AGE) - (GESTAGE_R_cont/52)),
    PREPREG_WEIGHT_A1 = case_when(PREPREG_WEIGHT_A1 == 99999 ~ NA, 
                                  TRUE ~ as.numeric(PREPREG_WEIGHT_A1)),
    PREPREG_WEIGHT_B1 = case_when(PREPREG_WEIGHT_B1 == 99999 ~ NA, 
                                  TRUE ~ as.numeric(PREPREG_WEIGHT_B1)),
    PREGWEIGHT_LBS_2 = case_when(PREGWEIGHT_LBS_2 == 99999 ~ NA, 
                                 TRUE ~ as.numeric(PREGWEIGHT_LBS_2)),
    PREGWEIGHT_KG_2 = case_when(PREGWEIGHT_KG_2 == 99999 ~ NA, 
                                TRUE ~ as.numeric(PREGWEIGHT_KG_2)),
    PREPREG_WEIGHT = case_when(is.na(PREPREG_WEIGHT_A1) ~ 2.20462 * PREPREG_WEIGHT_B1, 
                               !is.na(PREPREG_WEIGHT_A1) ~ PREPREG_WEIGHT_A1), 
    PREG_WEIGHT = case_when(is.na(PREGWEIGHT_LBS_2) ~ 2.20462 * PREGWEIGHT_KG_2, 
                            !is.na(PREGWEIGHT_LBS_2) ~ PREGWEIGHT_LBS_2), 
    WEIGHTGAIN_R = as.numeric(PREG_WEIGHT) - as.numeric(PREPREG_WEIGHT), 
    MARRIED = case_when(RELATIONSHIP == 1 ~ "Married",
                        RELATIONSHIP == 2 ~ "Committed Partner", 
                        RELATIONSHIP == 3 | RELATIONSHIP == 4 ~ "Separated/Single"),
    RACE = case_when(RACEALONE == 5 ~ "AIAN",
                     RACEALONE == 7 ~ "AIAN",
                     is.na(RACEALONE) ~ "Multi",
                     RACEALONE == 1 ~ "White",
                     RACEALONE == 2 ~ "Latina",
                     RACEALONE == 3 ~ "Black",
                     RACEALONE == 4 ~ "Asian",
                     RACEALONE == 6 ~ "MENA"),
    INSURANCE = case_when(INSURCAT == 1 ~ "Private",
                          INSURCAT == 2 ~ "Medicaid"),
    PROVIDER2 = case_when(PROVIDER == 1 ~ "OB",
                          PROVIDER == 4 ~ "Midwife",
                          PROVIDER %in% c(5,6) ~ "Other"),
    LABORWALK_NO = case_when(LABORWALK == 1 | LABORWALK == 3 ~ 0, 
                             LABORWALK == 2 ~ 1),
    BMI = PREPREG_WEIGHT *703 / HEIGHT^2, 
    DOULA = case_when(DOULAC1 == 1 ~ "Yes", 
                      DOULAC2 == 1 ~ "Yes", 
                      DOULAC3 == 1 ~ "Yes",
                      DOULAC4 == 1 ~ "No", 
                      DOULAC5 == 1 ~ "Missing", 
                      TRUE ~ "Missing"), 
    DOULAC1_V2 = case_when(DOULA == "Yes" & DOULAC1 == 1 ~ "During Pregnancy", 
                           DOULA == "Yes" & DOULAC1 == 0 ~ "Not During Pregnancy", 
                           DOULA == "No" | DOULA == "Missing" ~ NA),
    DOULAC2_V2 = case_when(DOULA == "Yes" & DOULAC2 == 1 ~ "During Birth", 
                           DOULA == "Yes" & DOULAC2 == 0 ~ "Not During Birth", 
                           DOULA == "No" | DOULA == "Missing" ~ NA),
    DOULAC3_V2 = case_when(DOULA == "Yes" & DOULAC3 == 1 ~ "Postpartum", 
                           DOULA == "Yes" & DOULAC3 == 0 ~ "Not Postpartum", 
                           DOULA == "No" | DOULA == "Missing" ~ NA), 
    LEARNED1 = case_when(LEARNED1 == 99 ~ NA, 
                         is.na(LEARNED1) ~ NA,
                         TRUE ~ as.numeric(LEARNED1)), 
    LEARNED2_R = case_when(LEARNED2 < 4 ~ "Less than 4 weeks",
                           LEARNED2 < 7 ~ "4 to 6 weeks", 
                           LEARNED2 < 9 ~ "7 to 8 weeks", 
                           LEARNED2 < 12 ~ "9 to 11 weeks", 
                           LEARNED2 >= 12 & LEARNED2 < 90 ~ "12 weeks or more"),
    PRENAT = case_when(LEARNED2 == 1 ~ "No Prenatal Care", 
                       LEARNED2 == 99 ~ "Missing", 
                       is.na(LEARNED2) ~ "Missing",
                       TRUE ~ "Had Prenatal Care"), 
    BIRTHWEIGHT_OZ = case_when(is.na(BIRTHWEIGHT_OZ) ~ 0,
                               BIRTHWEIGHT_OZ >= 99 ~ NA,
                               TRUE ~ BIRTHWEIGHT_OZ),
    BIRTHWEIGHT_LBS = case_when(BIRTHWEIGHT_LBS > 999 ~ NA, 
                                TRUE ~ BIRTHWEIGHT_LBS),
    BIRTHWEIGHT_G = case_when(BIRTHWEIGHT_G >= 99999 ~ NA, 
                              TRUE ~ BIRTHWEIGHT_G),
    BIRTHWEIGHT_LBSOZ = BIRTHWEIGHT_LBS + (BIRTHWEIGHT_OZ*0.0625),
    BIRTHWEIGHT = case_when(!is.na(BIRTHWEIGHT_LBS) ~ BIRTHWEIGHT_LBSOZ*453.592,
                            TRUE ~ BIRTHWEIGHT_G), 
    BIRTHWEIGHT = as.numeric(BIRTHWEIGHT),
    BIRTHWEIGHT_4500 = case_when(BIRTHWEIGHT >= 4500 ~ 1, 
                                 TRUE ~ 0),
    MACROSOMIC = case_when(BW_CAT == 4 ~ "Macro", 
                           BW_CAT < 4 ~ "Not Macro"),
    PROVIDER2 =case_when(PROVIDER %in% c(1)  ~ "OB",
                         PROVIDER == 4 ~ "Midwife",
                         PROVIDER %in% c(5,6) ~ "Other"), 
    BIRTHATTEND2 =case_when(BIRTHATTEND %in% c(1)  ~ "OB",
                            BIRTHATTEND == 4 ~ "Midwife",
                            BIRTHATTEND %in% c(5,6) ~ "Other"), 
    PPVISIT2 = case_when(PPVISIT >= 4 ~ 4,
                         TRUE ~ PPVISIT),
    PPVISIT_8 = case_when(PPVISIT >= 8 ~ 1, 
                           PPVISIT < 8 ~ 0),
    MEDINDUCE4 = case_when(MEDINDUCE4 >= 999 ~ NA, 
                           TRUE ~ MEDINDUCE4),
    LABORLENGTH = case_when(LABORLENGTH >= 999 ~ NA, 
                            TRUE ~ LABORLENGTH),
    MEDINDUCE5 = case_when(MEDINDUCE5 >= 999 ~ NA, 
                           TRUE ~ MEDINDUCE5),
    PLANNEDFEED_ONLY = case_when(PLANNEDFEEDC1 == 1 & PLANNEDFEEDC2 == 1 ~ "Both", 
                                 PLANNEDFEEDC1 == 1 & PLANNEDFEEDC2 == 0 ~ "Breastmilk", 
                                 PLANNEDFEEDC1 == 0 & PLANNEDFEEDC2 == 1 ~ "Formula"),
    FEED1WEEK_ONLY = case_when(FEED1WEEKC1 == 1 & FEED1WEEKC2 == 1 ~ "Both",
                               FEED1WEEKC1 == 1 & FEED1WEEKC2 == 0 ~ "Breastmilk",
                               FEED1WEEKC1 == 0 & FEED1WEEKC2 == 1 ~ "Formula"),
    FEED_CONCORDANT = case_when(PLANNEDFEEDC1 == 1 & FEED1WEEKC1 == 1 ~ 1, 
                                PLANNEDFEEDC2 == 1 & FEED1WEEKC2 == 1 ~ 1, 
                                PLANNEDFEEDC1 == 1 &  FEED1WEEKC2 == 1 ~ 0,
                                PLANNEDFEEDC2 == 1 &  FEED1WEEKC1 == 1 ~ 0),
    EXCL_BF_3MONTH = case_when(EXCLUSIVEBF < 3 ~ 0, 
                               EXCLUSIVEBF >= 3 ~ 1),
    BF_3MONTH = case_when(BF_MONTHS  == 1 ~ 0, 
                          BF_MONTHS == 2 ~ 0, 
                          BF_MONTHS %in% c(3,4,5) ~ 1),
    BABYHOSP = case_when(BABYHOSP >= 98 ~ NA, 
                         TRUE ~ BABYHOSP),
    DAYSHOSP = case_when(DAYSHOSP >= 98 ~ NA, 
                         TRUE ~ DAYSHOSP),
    ANYNICU = case_when(NICU %in% c(1,2) ~ "NICU", 
                        NICU == 3 ~ "No NICU"),
    PRENATAL_BIRTH = case_when(PROVIDER %in% c(1,2,3) & BIRTHATTEND %in% c(1,2,3) ~ "Phys/Phys",
                               PROVIDER %in% c(1,2,3) & BIRTHATTEND == 4 ~ "Phys/Midwife",
                               PROVIDER == 4 & BIRTHATTEND %in% c(1,2,3) ~ "Midwife/Phys",
                               PROVIDER == 4 & BIRTHATTEND == 4 ~ "Midwife/Midwife"),
    CSECTIONTYPE_R = case_when(CSECTIONTYPE == 2 ~ "Unplanned C-section", 
                               CSECTIONTYPE == 1 | CSECTIONTYPE == 95 ~ "Not Unplanned C-section",
                               MODE2023 == 1 ~ "Vaginal birth"),
    MODE = case_when(MODE == 1 ~ 0, 
                     MODE == 2 ~ 1),
    MODE2 = case_when(MODE2 == 1 ~ 0, 
                      MODE2 == 2 ~ 1),
    MODE3 = case_when(MODE3 == 1 ~ 0, 
                      MODE3 == 2 ~ 1),
    MODE4 = case_when(MODE4 == 1 ~ 0, 
                      MODE4 == 2 ~ 1),
    MODE5 = case_when(MODE5 == 1 ~ 0, 
                      MODE5 == 2 ~ 1),
    MODE6 = case_when(MODE6 == 1 ~ 0, 
                      MODE6 == 2 ~ 1),
    MODE7 = case_when(MODE7 == 1 ~ 0, 
                      MODE7 == 2 ~ 1),
    MODE8 = case_when(MODE8 == 1 ~ 0, 
                      MODE8 == 2 ~ 1),
    MODE9 = case_when(MODE9 == 1 ~ 0, 
                      MODE9 == 2 ~ 1),
    MODE10 = case_when(MODE10 == 1 ~ 0, 
                       MODE10 == 2 ~ 1),
    MODE11 = case_when(MODE11 == 1 ~ 0, 
                       MODE11 == 2 ~ 1),
    MODE12 = case_when(MODE12 == 1 ~ 0, 
                       MODE12 == 2 ~ 1),
    MODE13 = case_when(MODE13 == 1 ~ 0, 
                       MODE13 == 2 ~ 1),
    MODE14 = case_when(MODE14 == 1 ~ 0, 
                       MODE14 == 2 ~ 1),
    VBACEFFORT2 = case_when(VBACEFFORT %in% c(1,2,3) ~ "Tried Something", 
                            VBACEFFORT == 97 ~ "Tried Nothing"),
    ANYLABOR = case_when(MODE2023 == 1 ~ "Labored", 
                         MODE2023 == 2 & LABCSEC == 1 ~ "Labored", 
                         MODE2023 == 2 & LABCSEC == 2 ~ "No Labor"),
    PAINMEDSANY = case_when(PAINMEDSC1 == 1 ~ 1, 
                            PAINMEDSC2 == 1 ~ 1, 
                            PAINMEDSC3 == 1 ~ 1,
                            PAINMEDSC4 == 1 ~ 1,
                            PAINMEDSC5 == 1 ~ 1,
                            PAINMEDSC6 == 1 ~ 1, 
                            PAINMEDSC7 == 1 ~ 0),
    phys_cb = case_when(MEDINDUCE == 1 ~ "No", 
                        PAINMEDSANY == 1 ~ "No",
                        EPIST == 1 ~ "No",
                        xGESTAGE == 1 ~ "No",
                        MODE2023 == 2 ~ "No",
                        LABORINTC3 == 1 ~ "No",
                        LABORINTC1 == 1 ~ "No",
                        TRUE ~ "Yes"),
    SDM_1 = case_when(INDUCE1 == 1 ~ 1, 
                      INDUCE1 == 2 ~ 1, 
                      INDUCE1 == 3 ~ 0, 
                      INDUCE1 == 4 ~ 0),
    SDM_2 = case_when(INDUCE2 == 1 ~ 1, 
                      INDUCE2 == 2 ~ 1, 
                      INDUCE2 == 3 ~ 0, 
                      INDUCE2 == 4 ~ 0),
    SDM_3 = case_when(INDUCE3 == 1 ~ 1, 
                      INDUCE3 == 2 ~ 0),
    SDM_4 = case_when(INDUCE4 == 1 ~ 1, 
                      INDUCE4 == 2 ~ 0),
    BPCONFID = case_when(BPCONFID == 99 ~ NA,
                         TRUE ~ BPCONFID), 
    URINECONFID = case_when(URINECONFID == 99 ~ NA,
                            TRUE ~ URINECONFID),
    WEIGHCONFID = case_when(WEIGHCONFID == 99 ~ NA,
                            TRUE ~ WEIGHCONFID),
    BABYHRCONFID = case_when(BABYHRCONFID == 99 ~ NA,
                             TRUE ~ BABYHRCONFID), 
    CONFIDENCE_ANY = case_when(BPCONFID < 3  | URINECONFID < 3 | 
                                 WEIGHCONFID < 3 | BABYHRCONFID < 3 ~ "Yes",
                               is.na(BPCONFID) & is.na(URINECONFID) & 
                                 is.na(WEIGHCONFID) & is.na(BABYHRCONFID) ~ NA,
                               TRUE ~ "No"), 
    ATHOMECARE_ANY = case_when( ATHOMECAREC1 == 1 ~ 1, 
                                ATHOMECAREC2 == 1 ~ 1, 
                                ATHOMECAREC3 == 1 ~ 1,
                                ATHOMECAREC4 == 1 ~ 1, 
                                TRUE ~ 0), 
    CARETYPE_R = case_when(CARETYPEC1 == 1  & CARETYPEC2 == 0 ~ "Individual Only", 
                           CARETYPEC1 == 1 & CARETYPEC2 == 1 ~ "Both", 
                           CARETYPEC1 == 0 & CARETYPEC2 == 1 ~ "Group Only"), 
    CAREMODE_R = case_when(CAREMODEC1 == 1  & CAREMODEC2 == 0 ~ 1, 
                           CAREMODEC1 == 1 & CAREMODEC2 == 1 ~ 2, 
                           CAREMODEC1 == 0 & CAREMODEC2 == 1 ~ 3), 
    PREPREG_MHANY = case_when(PREPREG_MHCONDC1 == 1 ~ 1,
                              PREPREG_MHCONDC2 == 1 ~ 1,
                              PREPREG_MHCONDC3 == 1 ~ 1,
                              PREPREG_MHCONDC4 == 1 ~ 1,
                              PREPREG_MHCONDC5 == 1 ~ 1,
                              PREPREG_MHCONDC6 == 1 ~ 0),
    ANX_DEP = case_when(PREPREG_MHCONDC1 == 1 & PREPREG_MHCONDC2 == 1 ~ "Both Anxiety and Depression", 
                        PREPREG_MHCONDC1 == 1 ~ "Depression Only",
                        PREPREG_MHCONDC2 == 1 ~ "Anxiety Only",
                        PREPREG_MHCONDC2 == 0 & PREPREG_MHCONDC2 == 0 ~ "Neither"),
    MEDSANY = case_when(MENTALSUPPORT1C1 == 1 ~ 1,
                        MENTALSUPPORT1C2 == 1 ~ 1,
                        MENTALSUPPORT1C3 == 1 ~ 1,
                        MENTALSUPPORT1C4 == 1 ~ 1,
                        MENTALSUPPORT1C5 == 1 ~ 0), 
    MEDS_DEP_ANX = case_when(MENTALSUPPORT1C1 == 1 ~ 1,
                             MENTALSUPPORT1C2 == 1 ~ 1,
                             MENTALSUPPORT1C5 == 1 ~ 0, 
                             MENTALSUPPORT1C3 == 1 ~ 0, 
                             MENTALSUPPORT1C4 == 1 ~ 0),
    MSUPPORT_ANY = case_when(MEDS_DEP_ANX == 1 ~ 1, 
                             MENTALSUPPORT == 1 ~ 1,
                             MEDS_DEP_ANX == 0 & MENTALSUPPORT == 2 ~ 0),
    MSUPPORT_ONLY = case_when(MEDS_DEP_ANX == 1 & MENTALSUPPORT == 1 ~ "Counseling & Meds",
                              MEDS_DEP_ANX == 0 & MENTALSUPPORT == 1 ~ "Counseling Only",
                              MEDS_DEP_ANX == 1 & MENTALSUPPORT == 2 ~ "Meds Only", 
                              MEDS_DEP_ANX == 0 & MENTALSUPPORT == 2 ~ "Neither"),
    PREPREG_UNMET_NEEDS = case_when(MSUPPORT_ANY == 0 & PREPREG_MHCONDC1 == 1 ~ 1, 
                                    MSUPPORT_ANY == 0 & PREPREG_MHCONDC2 == 1 ~ 1, 
                                    MSUPPORT_ANY == 1 & PREPREG_MHCONDC1 == 1 ~ 0, 
                                    MSUPPORT_ANY == 1 & PREPREG_MHCONDC2 == 1 ~ 0),
    PPMEDS_ANY = case_when(PPMEDSC1 == 1 ~ 1,
                           PPMEDSC2 == 1 ~ 1,
                           PPMEDSC3 == 1 ~ 1,
                           PPMEDSC4 == 1 ~ 1,
                           PPMEDSC5 == 1 ~ 0),
    PPMEDS_DEP_ANX = case_when(PPMEDSC1 == 1 ~ 1,
                               PPMEDSC2 == 1 ~ 1,
                               PPMEDSC5 == 1 ~ 0, 
                               PPMEDSC3 == 1 ~ 0, 
                               PPMEDSC4 == 1 ~ 0),
    PP_MSUPPORT_ANY = case_when(PPTHERAPY == 1 ~ 1, 
                                PPMEDS_DEP_ANX == 1 ~ 1,
                                TRUE ~ 0),
    PP_MSUPPORT_ONLY = case_when(PPMEDS_DEP_ANX == 1 & PPTHERAPY == 1 ~ "Counseling & Meds",
                                 PPMEDS_DEP_ANX == 0 & PPTHERAPY == 1 ~ "Counseling Only",
                                 PPMEDS_DEP_ANX == 1 & PPTHERAPY == 2 ~ "Meds Only", 
                                 PPMEDS_DEP_ANX == 0 & PPTHERAPY == 2 ~ "Neither"),
    PP_UNMET_NEEDS = case_when(PP_MSUPPORT_ANY == 0 & PHQ4_PPDEP == 1 ~ 1, 
                                    PP_MSUPPORT_ANY == 0 & PHQ4_PPANX == 1 ~ 1, 
                                    PP_MSUPPORT_ANY == 1 & PHQ4_PPDEP == 1 ~ 0, 
                                    PP_MSUPPORT_ANY == 1 & PHQ4_PPANX == 1 ~ 0),
    CLASS_ANY = case_when(CURREDUC == 1 | PRIOREDUC == 1 ~ 1, 
                          PRIOREDUC == 2 & CURREDUC == 2 ~ 0), 
    INDUC_REC = case_when(BIGBABY2 == 1 ~ 1, 
                          BIGBABY1 == 1 & BIGBABY2 != 1 ~ 0), 
    CES_REC = case_when(BIGBABY2 == 2 ~ 1, 
                        BIGBABY1 == 1 & BIGBABY2 != 2 ~ 0), 
    WEIGHT_REC = case_when(BMI4_PREPREG == 1  & WEIGHTGAIN_R >= 28 & WEIGHTGAIN_R <= 40 ~ 1, 
                           BMI4_PREPREG == 1 & WEIGHTGAIN_R < 28 | WEIGHTGAIN_R > 40 ~ 0,
                           BMI4_PREPREG == 2  & WEIGHTGAIN_R >= 25 & WEIGHTGAIN_R <= 35 ~ 1,
                           BMI4_PREPREG == 2  & WEIGHTGAIN_R < 25 | WEIGHTGAIN_R > 35 ~ 0,
                           BMI4_PREPREG == 3  & WEIGHTGAIN_R >= 15 & WEIGHTGAIN_R <= 25 ~ 1, 
                           BMI4_PREPREG == 3  & WEIGHTGAIN_R < 15 | WEIGHTGAIN_R > 25 ~ 0,
                           BMI4_PREPREG == 4  & WEIGHTGAIN_R >= 11 & WEIGHTGAIN_R <= 20 ~ 1,
                           BMI4_PREPREG == 4  & WEIGHTGAIN_R < 11 | WEIGHTGAIN_R > 20 ~ 0), 
    
    WEIGHT_REC_D = case_when(BMI4_PREPREG == 1 & WEIGHTGAIN_R >= 28 & WEIGHTGAIN_R <= 40 ~ "Within",
                             BMI4_PREPREG == 1 & WEIGHTGAIN_R < 28 ~ "Below", 
                             BMI4_PREPREG == 1 & WEIGHTGAIN_R > 40 ~ "Above",
                             
                             BMI4_PREPREG == 2  & WEIGHTGAIN_R >= 25 & WEIGHTGAIN_R <= 35 ~ "Within",
                             BMI4_PREPREG == 2  & WEIGHTGAIN_R < 25 ~ "Below",
                             BMI4_PREPREG == 2  & WEIGHTGAIN_R > 35 ~ "Above",
                             
                             BMI4_PREPREG == 3  & WEIGHTGAIN_R >= 15 & WEIGHTGAIN_R <= 25 ~ "Within", 
                             BMI4_PREPREG == 3  & WEIGHTGAIN_R < 15 ~ "Below",
                             BMI4_PREPREG == 3  & WEIGHTGAIN_R > 25 ~ "Above",
                             
                             BMI4_PREPREG == 4  & WEIGHTGAIN_R >= 11 & WEIGHTGAIN_R <= 20 ~ "Within",
                             BMI4_PREPREG == 4  & WEIGHTGAIN_R < 11 ~ "Below",
                             BMI4_PREPREG == 4  & WEIGHTGAIN_R > 20 ~ "Above"), 
    NEITHER = case_when(MEDINDUCE == 1 ~ 0, 
                        MODE2023 == 2 ~ 0, 
                        MEDINDUCE == 0 ~ 1, 
                        MODE2023 == 1 ~ 1), 
    NEITHER_REC = case_when(BIGBABY2 == 1 | BIGBABY2 == 2 ~ 0, 
                            BIGBABY2 == 97 ~ 1),
    PLANNED_INDUCED = case_when(MEDINDUCE == 1 ~ 1, # induced 
                                CSECTIONTYPE == 1 ~ 1, # planned cesarean 
                                MEDINDUCE != 1 & CSECTIONTYPE != 1 ~ 0), # no induction and not planned cesarean
    OTHERSUPPORT_ONLY = case_when(OTHERSUPPORTC1 == 1 & OTHERSUPPORTC2 == 0 ~ "Spouse",
                                  OTHERSUPPORTC1 == 0 & OTHERSUPPORTC2 == 1 ~ "Family", 
                                  OTHERSUPPORTC1 == 1 & OTHERSUPPORTC2 == 1 ~ "Both",
                                  OTHERSUPPORTC3 == 1 ~ "Neither"),
    DENIED = case_when(LABORPERMIT_A1 == 3 | LABORPERMIT_A2 == 3 ~ 1,
                       LABORPERMIT_A1 < 3 & LABORPERMIT_A2 < 3 ~ 0),
    COMPOSITE = case_when(xGESTAGE == 1 & BW_CAT %in% c(3,4)~ "Preterm & Normal Birthweight", 
                          xGESTAGE == 1 & BW_CAT %in% c(1,2)~ "Preterm & Low Birthweight", 
                          xGESTAGE > 1 & BW_CAT %in% c(3,4)~ "Term & Normal Birthweight", 
                          xGESTAGE > 1 & BW_CAT %in% c(1,2)~ "Term & Low Birthweight"),
    DOULA_CAROL = case_when(DOULAC1 == 1 & DOULAC2 == 1 & DOULAC3 == 1 ~ "pregnancy, birth, postpartum",
                            DOULAC1 == 1 & DOULAC2 == 1 & DOULAC3 == 0 ~ "pregnancy, birth",
                            DOULAC1 == 1 & DOULAC2 == 0 & DOULAC3 == 0 ~ "pregnancy only",
                            DOULAC1 == 1 & DOULAC2 == 0 & DOULAC3 == 1 ~ "pregnancy, postpartum",
                            DOULAC1 == 0 & DOULAC2 == 1 & DOULAC3 == 1 ~ "birth, postpartum",
                            DOULAC1 == 0 & DOULAC2 == 1 & DOULAC3 == 0 ~ "birth only",
                            DOULAC1 == 0 & DOULAC2 == 0 & DOULAC3 == 1 ~ "postpartum only",
                            DOULAC1 == 0 & DOULAC2 == 0 & DOULAC3 == 0 ~ "No Doula"), 
    RHOSPFEEDC7 = case_when(HOSPFEEDC7 == 1 ~ 0, 
                            HOSPFEEDC7 == 0 ~ 1),
    RHOSPFEEDC6 = case_when(HOSPFEEDC6 == 1 ~ 0, 
                            HOSPFEEDC6 == 0 ~ 1), 
    RHOSPFEEDC4 = case_when(HOSPFEEDC4 == 1 ~ 0, 
                            HOSPFEEDC4 == 0 ~ 1), 
    LABORINTC1 = case_when(LABORINTC1 > 1 ~ NA, 
                           TRUE ~ LABORINTC1),
    LABORINTC2 = case_when(LABORINTC2 > 1 ~ NA, 
                           TRUE ~ LABORINTC2),
    LABORINTC3 = case_when(LABORINTC3 > 1 ~ NA, 
                           TRUE ~ LABORINTC3),
    LABORINTC4 = case_when(LABORINTC4 > 1 ~ NA, 
                           TRUE ~ LABORINTC4),
    LABORINTC5 = case_when(LABORINTC5 > 1 ~ NA, 
                           TRUE ~ LABORINTC5),
    LABORINTC6 = case_when(LABORINTC6 > 1 ~ NA, 
                           TRUE ~ LABORINTC6),
    LABORINTC7 = case_when(LABORINTC7 > 1 ~ NA, 
                           TRUE ~ LABORINTC7),
    LABORED = case_when(MODE2023 == 1 | LABCSEC == 1 ~ 1, 
                        TRUE ~ 0),
    PITOCIN = case_when(LABORINTC3 == 1 ~ 1, 
                        MEDINDUCE1C4 == 1 ~ 1, 
                        TRUE ~ 0),
    AUGMENT = case_when(LABORINTC1 == 1 | LABORINTC3 == 1 ~ 1, 
                        LABORED == 1 & LABORINTC1 != 1 & LABORINTC3 != 1 ~ 0),
    BLADDER = case_when(LABORINTC4 == 1 | CSECTIONINTC2 == 1 ~ 1, 
                        TRUE ~ 0),
    IV_DRIP = case_when(CSECTIONINTC1 == 1 | LABORINTC2 == 1 ~ 1, 
                        TRUE ~ 0),
    R_LABORINTC6 = case_when(LABORINTC6 == 1 & FETALMONC1 == 1 ~ 0, 
                             LABORINTC6 == 1 & FETALMONC1 != 1 ~ 1, 
                             LABORINTC6 == 0 ~ 0),
    AROM_ANY = case_when(LABORINTC1 == 1 & MEDINDUCE1C1 == 1 ~ "AROM Induction", 
                         LABORINTC1 == 0 & MEDINDUCE1C1 == 1 ~ "AROM Augmentation",
                         LABORINTC1 == 1 & MEDINDUCE1C1 == 0 ~ "AROM Induction",
                         MEDINDUCE1C1 == 0 & LABORINTC1 == 0 ~ "No AROM"),
    VAGEXAM2 = case_when(VAGEXAM == 99999 ~ NA, 
                         VAGEXAM >= 7 & VAGEXAM <= 10 ~ "7",
                         TRUE ~ factor(VAGEXAM)),
    VAGEXAM_4 = case_when(VAGEXAM <= 4 ~ "≤ 4", 
                          VAGEXAM > 4 & VAGEXAM <= 10 ~ "5+"),
    VAGEXAM_5 = case_when(VAGEXAM <= 5 ~ 1, 
                          VAGEXAM > 5 & VAGEXAM <= 10 ~ 0),
    AROM_LABOR = case_when(LABORINTC1 == 1 & LABORINTC3 == 1 ~ "Both", 
                           LABORINTC1 == 0 & LABORINTC3 == 1 ~ "Pit Only",
                           LABORINTC1 == 1 & LABORINTC3 == 0 ~ "AROM only", 
                           LABORINTC1 == 0 & LABORINTC3 == 0 ~ "Neither"), 
    FETALMON_ONLY = case_when(FETALMONC1 == 1 & FETALMONC2 == 1 ~ "Both", 
                              FETALMONC1 == 1 & FETALMONC2 == 0 ~ "EFM", 
                              FETALMONC1 == 0 & FETALMONC2 == 1 ~ "Doppler",
                              FETALMONC1 == 1 & FETALMONC2 == 1 ~ "Neither"),
    DISCRIMINATION_R = case_when(DISCRIMINATION == 1 ~ 4, 
                                 DISCRIMINATION == 2 ~ 3, 
                                 DISCRIMINATION == 3 ~ 2, 
                                 DISCRIMINATION == 4 ~ 1),
    NEGLECT_R = case_when(NEGLECT == 1 ~ 4, 
                          NEGLECT == 2 ~ 3, 
                          NEGLECT == 3 ~ 2,
                          NEGLECT == 4 ~ 1),
    CUM_IND = case_when(MEDINDUCE == 2 ~ 0, 
                        MEDINDUCE == 1 ~ 1),
    CUM_EPI = case_when(PAINMEDSC1 == 1 ~ 1, 
                        TRUE ~ 0), 
    CUM_AUG = case_when(LABORINTC1 == 1 ~ 1, 
                        LABORINTC3 == 1 ~ 1, 
                        TRUE ~ 0), 
    CUM_ASS = case_when(VAGASSIST == 1 ~ 1, 
                        VAGASSIST == 2 ~ 1,
                        TRUE ~ 0), 
    ASSISTED = case_when(VAGASSIST == 1 ~ "Assisted", 
                        VAGASSIST == 2 ~ "Assisted",
                        VAGASSIST == 3 ~ "Unassisted",
                        VAGASSIST == 99 ~ "PNTA"), 
    CUM_CES = case_when(MODE2023 == 2 ~ 1, 
                        TRUE ~ 0), 
    CUSTOMS2 = case_when(CUSTOMS > 90 ~ NA, 
                         TRUE ~ CUSTOMS)) %>% 
  rename(MDE2023 = MODE2023, 
         SONEEDC11 = SOCIALNEEDC11,
         SONEEDC10 = SOCIALNEEDC10, 
         HSPFEEDC8 = HOSPFEEDC8,
         HSPFEEDC11 = HOSPFEEDC11,
         HSPFEEDC12 = HOSPFEEDC12, 
         HSPFEEDC4 = HOSPFEEDC4, 
         HSPFEEDC6 = HOSPFEEDC6,
         HSPFEEDC7 = HOSPFEEDC7, 
         HOSPFEEDC4 = RHOSPFEEDC4,
         HOSPFEEDC6 = RHOSPFEEDC6,
         HOSPFEEDC7 = RHOSPFEEDC7) %>%
  rowwise() %>% 
  mutate(MODE_ALL = sum(across(starts_with("MODE")), na.rm = T),
         SUM_SOCIALNEED =sum(across(starts_with("SOCIALNEED")), na.rm = T),
         SUM_HOSPFEED = sum(across(starts_with("HOSPFEED")), na.rm = T),
         SUM_SNNEEDS = sum(across(starts_with("SN")), na.rm = T),
         SDM = sum(SDM_1,SDM_2,SDM_3,SDM_4, na.rm = T), 
         SUM_ANX = sum(BOTHER_R1, BOTHER_R2, na.rm = T), 
         SUM_DEP = sum(BOTHER_R3, BOTHER_R4, na.rm = T), 
         SUM_PHQ4 = sum(across(starts_with("BOTHER_R"))), 
         SUM_DRUGFREE = sum(DRUGFREEC1,DRUGFREEC2,DRUGFREEC3,DRUGFREEC4,
                            DRUGFREEC5,DRUGFREEC6,DRUGFREEC7,DRUGFREEC8,
                            DRUGFREEC9,DRUGFREEC10), # including other
         SUM_LABORINT = sum(LABORINTC1, LABORINTC2, LABORINTC3, 
                            LABORINTC4, LABORINTC5, FETALMONC1, LABORWALK_NO, 
                            VAGEXAM_5, DENIED), 
         CUM_INT = sum(across(starts_with("CUM_"))) # Induction, epidural, augmentation, assisted, cesarean
  )

LTM2 <- LTM2 %>% 
  mutate(VAGEXAM_5 = case_when(VAGEXAM_5 == 1 ~ "Early Labor", 
                               VAGEXAM_5 == 0 ~ "Not Early Labor"), 
         VBAC = case_when(MODE_ALL > 0 & MDE2023 == 1 ~ 1,
                          MODE_ALL > 0 & MDE2023 == 2 ~ 0,
                          MODE_ALL == 0 ~ 0),
         PRIOR_C = case_when(xMODE2 == 4 ~ 1, 
                             xMODE2 == 2 ~ 1, 
                             xMODE2 == 1 ~ 0, 
                             xMODE2 == 3 ~ 0),
         SDM = case_when(is.na(SDM_1)~NA,
                         is.na(SDM_2)~NA,
                         is.na(SDM_3)~NA,
                         is.na(SDM_4)~NA, 
                         TRUE ~ SDM), 
         SDM_dich = case_when(SDM == 0 ~ 0, 
                              SDM > 0 ~ 1),
         # SUM_PCMC = case_when(SUM_PCMC == 12),
         R_PHQ_ANX = case_when(SUM_ANX < 3 ~ 0, 
                               SUM_ANX >= 3 ~ 1),
         R_PHQ_DEP = case_when(SUM_DEP < 3 ~ 0, 
                               SUM_DEP >= 3 ~ 1),
         R_PHQ4 = case_when(SUM_PHQ4 <= 2 ~ "Normal", 
                            SUM_PHQ4 <= 5 ~ "Mild", 
                            SUM_PHQ4 <= 8 ~ "Moderate", 
                            SUM_PHQ4 <= 12 ~ "Severe"),
         R_PHQ_DISC = case_when(R_PHQ_ANX == 1 & R_PHQ_DEP == 1 ~ "Pregnancy Depression and Anxiety",
                                R_PHQ_ANX == 1 & R_PHQ_DEP == 0 ~ "Pregnancy Anxiety Only",
                                R_PHQ_ANX == 0 & R_PHQ_DEP == 1 ~ "Pregnancy Depression Only",
                                R_PHQ_ANX == 0 & R_PHQ_DEP == 0 ~ "Neither"),
         PREG_UNMET_NEEDS = case_when(MEDS_DEP_ANX == 0 & R_PHQ_DEP == 1 ~ 1, 
                                      MEDS_DEP_ANX == 0 & R_PHQ_ANX == 1 ~ 1, 
                                      MEDS_DEP_ANX == 1 & R_PHQ_DEP == 1 ~ 0, 
                                      MEDS_DEP_ANX == 1 & R_PHQ_ANX == 1 ~ 0, 
                                      R_PHQ_ANX == 0 ~ NA,
                                      R_PHQ_DEP == 0 ~ NA),
         MIDWIFE_DOULA = case_when(BIRTHATTEND2 == "Midwife" & DOULAC2 == 1 ~ "Midwife & Doula", 
                                   BIRTHATTEND2 != "Midwife" & DOULAC2 != 1 ~ "No Midwife & No Doula"), 
         TRI_DOULA = case_when(DOULAC1 == 1 & DOULAC2 == 1 & PROVIDER == 4 ~ 1, 
                               TRUE ~ 0),
         MDID = as.numeric(MDID),
         SUM_HOSPFEED = case_when(SUM_HOSPFEED > 10 ~ NA, 
                                  TRUE ~ SUM_HOSPFEED),
         SUM_HOSPFEED = as.numeric(SUM_HOSPFEED),
         HOSPFEED2 = case_when(SUM_HOSPFEED == 0 | SUM_HOSPFEED == 1 ~ "0-1", 
                                   SUM_HOSPFEED ==2 | SUM_HOSPFEED == 3 ~ "2-3",
                                   SUM_HOSPFEED == 4 | SUM_HOSPFEED == 5 ~ "4-5", 
                                   SUM_HOSPFEED == 6 | SUM_HOSPFEED == 7 ~ "6-7", 
                                   SUM_HOSPFEED == 8 | SUM_HOSPFEED == 9 ~ "8-9"),
         RHOSPFEEDC11 = case_when(SUM_HOSPFEED == 0 ~ 1,
                                  SUM_HOSPFEED > 0 ~ 0),
         SUM_SNNEEDS = case_when(SUM_SNNEEDS > 10 ~ NA, 
                                 TRUE ~ SUM_SNNEEDS), 
         CAT_SNNEEDS = case_when(SUM_SNNEEDS == 0 ~ 0, SUM_SNNEEDS > 0 ~ 1), 
         LABORINT_ALL = case_when(SUM_LABORINT == 6 ~ 1, 
                                  SUM_LABORINT < 6 ~ 0)) %>%
  # select(-c(HOSPFEEDC6, HOSPFEEDC7,HOSPFEEDC4)) %>%
  rename(MODE2023 = MDE2023,
         SOCIALNEEDC11 = SONEEDC11,
         SOCIALNEEDC10 = SONEEDC10, 
         HOSPFEEDC8 = HSPFEEDC8,
         HOSPFEEDC11 = HSPFEEDC11,
         HOSPFEEDC12 = HSPFEEDC12, 
         RHOSPFEEDC4 = HOSPFEEDC4,
         RHOSPFEEDC6 = HOSPFEEDC6,
         RHOSPFEEDC7 = HOSPFEEDC7,
         HOSPFEEDC4 = HSPFEEDC4,
         HOSPFEEDC6 = HSPFEEDC6,
         HOSPFEEDC7 = HSPFEEDC7)

# Scoring for PCMC ----
PCMC <- c('RESPECT', 'KNOWLEDGE', 'HEARD',
          'DECISIONS', 'CONSENT', 'INFORMED',
          'TRUST', 'FEEDING', 'SAFE')
for(i in PCMC){
  LTM2[,paste0(i, "_pcmc")] <- pcmc.score(i)
}

LTM2 <- LTM2 %>%
  mutate(CUSTOMS_subopt = case_when(CUSTOMS == 1 ~ 1, 
                                    CUSTOMS == 2 ~ 1, 
                                    CUSTOMS == 3 ~ 1, 
                                    CUSTOMS == 4 ~ 0), 
         CUSTOMS_pcmc = case_when(CUSTOMS == 1 ~ 0, 
                                  CUSTOMS == 2 ~ 1, 
                                  CUSTOMS == 3 ~ 2, 
                                  CUSTOMS == 4 ~ 3, 
                                  CUSTOMS == 97 ~ 2), 
         TIMELINESS_pcmc = case_when(TIMELINESS == 1 ~ 0, 
                                     TIMELINESS == 2 ~ 1, 
                                     TIMELINESS == 3 ~ 2, 
                                     TIMELINESS == 4 ~ 3, 
                                     TIMELINESS == 97 ~ 2),
         DISCRIMINATION_pcmc = case_when(DISCRIMINATION == 1 ~ 3, 
                                         DISCRIMINATION == 2 ~ 2,
                                         DISCRIMINATION == 3 ~ 1, 
                                         DISCRIMINATION == 4 ~ 0),
         NEGLECT_pcmc = case_when(NEGLECT == 1 ~ 3, 
                                  NEGLECT == 2 ~ 2,
                                  NEGLECT == 3 ~ 1, 
                                  NEGLECT == 4 ~ 0)) %>%
  rowwise() %>%
  mutate(PCMC_SCORE = sum(across(ends_with("_pcmc"))), 
         PCMC_resp = sum(RESPECT_pcmc, KNOWLEDGE_pcmc, CUSTOMS_pcmc, 
                         DISCRIMINATION_pcmc, NEGLECT_pcmc, na.rm = T), 
         PCMC_comms = sum(HEARD_pcmc, DECISIONS_pcmc, 
                          CONSENT_pcmc, INFORMED_pcmc, na.rm = T), 
         PCMC_supp = TIMELINESS_pcmc+TRUST_pcmc+SAFE_pcmc+FEEDING_pcmc)

LTM2 <- LTM2 %>% 
  mutate(PCMC_SCORE = 100*round(PCMC_SCORE/39,2), 
         PCMC_resp = 100*round(PCMC_resp/15,2),
         PCMC_comms = 100*round(PCMC_comms/12,2),
         PCMC_supp = 100*round(PCMC_supp/12,2))

# Changing 0 back to 2 for data dictionary application ----
for(i in sn_cols){
  LTM2[[i]] <- ifelse(LTM2[[i]] == 0, 2, LTM2[[i]])
}

# Exporting ----
LTM2 <- as.data.frame(LTM2)

# setwd("~/Documents/2025-2026/LTM/Listening-to-Mothers")
# write.csv(LTM2, "LTM_clean.csv")


