LTM2 <- LTM2 %>% 
  mutate(DUEDATE_Y = as.numeric(DUEDATE_Y),
         DUEDATE_M_NUM = case_when(DUEDATE_M == 1 ~ 1,
                                   DUEDATE_M == 2 ~ 2, 
                                   DUEDATE_M == 3 ~ 3, 
                                   DUEDATE_M == 4 ~ 4, 
                                   DUEDATE_M == 5 ~ 5, 
                                   DUEDATE_M == 6 ~ 6, 
                                   DUEDATE_M == 7 ~ 7, 
                                   DUEDATE_M == 8 ~ 8, 
                                   DUEDATE_M == 9 ~ 9, 
                                   DUEDATE_M == 10 ~ 10, 
                                   DUEDATE_M == 11 ~ 11, 
                                   DUEDATE_M == 12 ~ 12),
         DUEDATE_D = as.numeric(DUEDATE_D),
         DUEDATE = as.Date(paste0(DUEDATE_M_NUM,"/", DUEDATE_D, "/",DUEDATE_Y), "m%/%d/%Y"),
         YEARBIRTH = as.numeric(YEARBIRTH),
         BIRTHDATE_M_NUM = case_when(BIRTHDATE_M == 1 ~ '01',
                                     BIRTHDATE_M == 2 ~ '02', 
                                     BIRTHDATE_M == 3 ~ '03', 
                                     BIRTHDATE_M == 4 ~ '04', 
                                     BIRTHDATE_M == 5 ~ '05', 
                                     BIRTHDATE_M == 6 ~ '06', 
                                     BIRTHDATE_M == 7 ~ '07', 
                                     BIRTHDATE_M == 8 ~ '08', 
                                     BIRTHDATE_M == 9 ~ '09', 
                                     BIRTHDATE_M == 10 ~ '10', 
                                     BIRTHDATE_M == 11 ~ '11', 
                                     BIRTHDATE_M == 12 ~ '12'),
         BIRTHDATE_D = case_when(nchar(BIRTHDATE_D) == 1 ~ paste0("0",BIRTHDATE_D),
                                 TRUE ~ as.character(BIRTHDATE_D)),
         BIRTHDATE_T = paste0(YEARBIRTH,BIRTHDATE_M_NUM,BIRTHDATE_D),
         BIRTHDATE = as.Date(BIRTHDATE_T, "%Y%m%d"), 
         LastConnectionDate = case_when(grepl("/", LastConnectionDate) ~ gsub("/","", LastConnectionDate),
                                        TRUE ~ as.character(LastConnectionDate)),
         SURVEYDATE = as.Date(LastConnectionDate, "%Y%m%d"), 
         TIME_SINCE_BIRTH = difftime(SURVEYDATE, BIRTHDATE, units = "weeks"),
         TIME_SINCE_BIRTH = as.numeric(TIME_SINCE_BIRTH))
