---
title: "Comparisons by Group"
author: "Ruby Barnard-Mayers"
date: "2025-10-14"
output: html_document
---

```{r setup, include = F}
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Cleaning/ApplyDictionary.R")
source("~/Documents/2025-2026/LTM/Listening-to-Mothers/Cleaning/ChapterVariables.R")
library(survey)
library(tableone)
library(ggplot2)
library(kableExtra)
library(gtsummary)
library(tidyr)
library(ggsurvey)
library(rlang)
library(knitr)
```

```{r, echo = F, warning=F, message = F}
LTM_dsn %>% 
  tbl_svysummary(
    by = RACE,
    include = c(cat_1, cont_1,cat_2,cont_2, cat_3, cont_3, cat_4, cont_4),
    statistic =  list(all_categorical() ~ "{p}%"),
    all_continuous()  ~ "{mean} ({sd})",
  ) %>%
  modify_header(
    #label = "**Variable**",
    all_stat_cols() ~ "**{level}**<br>{style_percent(p, digits=0)}%") %>%
  modify_caption("Weighted descriptive statistics, by race") %>%
  bold_labels()
```

```{r, echo = F, warning=F, message = F, eval = F}
LTM_dsn %>% 
  tbl_svysummary(
    by = INSURANCE,
    include = c(cat_1, cont_1,cat_2,cont_2, cat_3, cont_3, cat_4, cont_4),
    statistic =  list(all_categorical() ~ "{p}%"),
    all_continuous()  ~ "{mean} ({sd})",
  ) %>%
  modify_header(label = "**Variable**",
                all_stat_cols() ~ "**{level}**<br>{style_percent(p, digits=0)}%") %>%
  modify_caption("Weighted descriptive statistics, by insurance") %>%
  bold_labels()
```
